services:
  mysql:
    container_name: postgres-container
    image: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: MangEmployee
    ports:
      - 5434:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
volumes:
  postgres-data:
